### ISSUE TITLE
What is the tfeat?thank you.

### ISSUE THREAD

**Issue by JasonZhangS** [scape-research/SOSNet#7]
what is is the tfeat in your sample code?

**Comment by valavanisleonidas** [comment]
Tfeat is another network for learning local descriptors. it is explained [here](http://www.bmva.org/bmvc/2016/papers/paper119/paper119.pdf) in details and the repo is available [here](https://github.com/vbalnt/tfeat) . SOSNet performs better but tfeat analyzes more basic concepts in my opinion
